services:
  web:
    image: php:8.2.30-apache
    container_name: php_apache
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html

  db:
    image: mariadb:10.3.39
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: "projekti"
      MARIABD_DATABASE: "projekti"
      MARIADB_USER: "projekti"
      MARIADB_PASSWORD: "projekti"
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
       PMA_HOST: "db"
       PMA_PORT: 3306
       PMA_USER: "projekti"
       PMA_PASSWORD: "projekti"
