services:
  db:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: "projekti"
      MARIABD_DATABASE: "projekti"
    ports:
      - "3306:3306"

  web:
    image: php:8.2.30-apache
    container_name: php_apache
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: "db"
      PMA_PORT: 3306
      PMA_USER: "root"
      PMA_PASSWORD: "projekti"
