version: '3.8'

services:
  web:
    image: php:8.2.30-apache
    container_name: php_apache
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html

  db:
    image: mariadb:10.3.39
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: projekti
      MYSQL_DATABASE: projekti
      MYSQL_USER: projekti
      MYSQL_PASSWORD: projekti
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
